<strong>NBExtensions<strong>

In [1]:
#nbextensions
#Run the following in your command prompt
#!pip install jupyter_nbextensions_configurator
#https://medium.com/@rrfd/jupyter-notebook-shortcuts-tips-and-tricks-top-nbextensions-bring-order-to-your-notebooks-pt-1-b58f270963f9

In [1]:
import pandas as pd
xlsx = pd.ExcelFile('C:/Users/Michael/Dropbox/PhD/CU/0 - Courses/1- Fall 2018/Group Project - Solar Desal/Datasets/2 - Water Stress WRI/aqueduct_countries_20140109.xlsx')
df1 = pd.read_excel(xlsx, 'Baseline Water Stress')
df2 = pd.read_excel(xlsx, 'Drought Severity')

1.) <strong>Baseline Water Stress <strong>

In [2]:
#Baseline Water Stress
df1.head()

,Rank,Name,All sectors,sd,nodata,0,5,1,15,2,25,3,35,4,45,hist,Agricultural,Domestic,Industrial
0,1,Antigua and Barbuda,5,0,0,0,0,0,0,0,0,0,0,0,8026709,NaN,5,5,5
1,1,Bahrain,5,0,0,0,0,0,0,0,0,0,0,0,413053888,NaN,5,5,5
2,1,Barbados,5,0,0,0,0,0,0,0,0,0,0,0,69750728,NaN,5,5,5
3,1,Comoros,5,0,0,0,0,0,0,0,0,0,0,0,11226803,NaN,5,5,5
4,1,Cyprus,5,0,0,0,0,0,0,0,0,0,0,0,97815136,NaN,5,5,5

In [3]:
df1["All sectors"].describe()

count     200
unique    162
top         -
freq       20
Name: All sectors, dtype: object

In [4]:
df1.set_index("Name",inplace=True)

In [5]:
#Shows countries with greatest to lowest water stress (5 = highest, 0 = lowest)
df1["All sectors"]

Name
Antigua and Barbuda                           5
Bahrain                                       5
Barbados                                      5
Comoros                                       5
Cyprus                                        5
Dominica                                      5
Jamaica                                       5
Malta                                         5
Qatar                                         5
Saint Lucia                                   5
Saint Vincent and the Grenadines              5
San Marino                                    5
Singapore                                     5
Trinidad and Tobago                           5
United Arab Emirates                          5
Western Sahara                                5
Saudi Arabia                            4.99235
Kuwait                                  4.96487
Oman                                    4.91379
Libya                                   4.84021
Israel                                  4.82539
Kyrgyzstan                                4.822
East Timor                              4.80609
Iran                                    4.78155
Yemen                                   4.67405
Palestine                               4.63391
Jordan                                  4.59445
Lebanon                                   4.541
Somaliland                              4.37948
Uzbekistan                              4.31667
                                       ...
Paraguay                              0.0111503
Brunei                               0.00837207
Democratic Republic of the Congo     0.00604593
Uganda                              0.000342989
Burkina Faso                           4.45e-06
Benin                                         0
Burundi                                       0
Central African Republic                      0
Rwanda                                        0
South Sudan                                   0
Cape Verde                                    -
Curacao                                       -
Federated States of Micronesia                -
Fiji                                          -
Grenada                                       -
Kiribati                                      -
Maldives                                      -
Marshall Islands                              -
Mauritius                                     -
Nauru                                         -
Palau                                         -
Saint Kitts and Nevis                         -
Samoa                                         -
Sao Tome and Principe                         -
Seychelles                                    -
Solomon Islands                               -
The Bahamas                                   -
Tonga                                         -
Tuvalu                                        -
Vanuatu                                       -
Name: All sectors, Length: 200, dtype: object

2.) <strong>Drought Severity <strong>

Drought severity measures the average length of drought times the dryness of the droughts from 1901 to 2008. Drought is defined as a contiguous period when soil moisture remains below the 20th percentile. Length is measured in month and dryness is the average number of percentage points by which soil moisture drops below the 20th percentile.

In [16]:
df2.set_index("Name",inplace=True)
df2

,Rank,All sectors,sd,nodata,0,5,1,15,2,25,3,35,4,45,hist,Agricultural,Domestic,Industrial
Name,,,,,,,,,,,,,,,,,,
Western Sahara,1,4.42071,0.768368,0,0,0,0,0,0,0,2240,0,0,4187,NaN,-,4.6669,-
Mauritania,2,3.79019,0.556042,0,213103,68,0,0,15015023,5311185,193063936,1029178304,27249688,257697616,NaN,3.76468,4.03229,4.18746
Niger,3,3.72379,0.797328,0,0,0,1018,142785,7111591,410962976,308104448,563758144,30930076,344561408,NaN,3.57845,4.1901,3.59054
Senegal,4,3.64657,0.99959,0,0,0,0,313544768,35064292,173029264,957396,1027470272,0,661242240,NaN,3.71247,3.09595,3.20644
Oman,5,3.41492,0.800593,0,5934516,0,106059,60064496,265336880,62856892,235582000,542186240,101497696,157366064,NaN,3.39363,3.45855,3.7245
Peru,6,3.38979,1.37898,0,700552576,267940544,920185408,3133602304,455007456,2701303552,1674152832,537297408,3263563776,6703970304,NaN,3.52807,2.75157,3.20099
Egypt,7,3.35266,0.757048,0,331971872,29458004,2703615,678048256,560444480,2022756608,44208959488,4063433472,188638160,8666412032,NaN,3.33351,3.41698,3.42021
Namibia,8,3.299,0.834018,0,124506,12483,48276,56290,62486824,72965744,74841352,79734160,6108686,43386996,NaN,2.93476,3.81333,3.77499
Qatar,9,2.94453,0.618648,0,0,1697681,25737056,0,181215168,0,413682816,38148560,7093097,0,NaN,2.66411,3.19129,2.98151
Sudan,10,2.94119,0.780725,0,0,145747,676655,2211904000,4908194304,5558996480,11672890368,1161804800,70261200,2521998336,NaN,2.88018,3.20286,3.62236
United Arab Emirates,11,2.91875,1.31171,0,578003200,260930752,179802752,263210592,209992192,481507040,1274178816,1140986368,1170531968,6894871,NaN,3.2212,2.1809,2.67397
Mali,12,2.90066,1.08793,0,661452,218440560,319427936,233234336,1608446208,240689616,174769744,505374240,1551335936,49723040,NaN,3.11636,2.48112,2.22388
Armenia,13,2.82779,0.33097,0,0,0,425753,0,707530816,171300688,1570004096,0,0,0,NaN,2.82861,2.81812,2.88019
Jordan,14,2.80048,0.340341,0,0,0,0,7045952,284204,1011965440,107286304,0,53435108,1428509,NaN,2.8598,2.69422,2.73408
Libya,15,2.76611,1.2509,0,150249760,0,33140640,1959925248,956159872,1389480448,130112960,237400512,17548,1270322560,NaN,2.81148,2.50097,2.80523
Eritrea,16,2.72977,0.82971,0,3470655,19977950,54388732,31953492,4065217,124379400,293641824,586044,0,0,NaN,2.71438,2.90811,2.17071
Botswana,17,2.70227,0.472992,0,0,0,0,22637984,5882220,155179424,27405512,12701358,1983594,1172510,NaN,2.40373,2.86163,2.77158
Ecuador,18,2.64303,1.09633,0,8441426,1760328832,3658831360,544287040,623955456,1692477312,1088202880,6635730432,845989376,0,NaN,2.70014,2.39624,2.0638
Turkmenistan,19,2.61929,0.584604,0,42067168,28285786,116080704,5035060224,4582809600,9152154624,927366464,4172387840,0,0,NaN,2.64093,2.40132,2.17091
Iran,20,2.57415,0.518369,0,60130152,193730928,2596559360,6520094720,30129852416,29415876608,18957328384,1017153280,586519680,0,NaN,2.57896,2.53333,2.52549
Uzbekistan,21,2.56691,0.324003,0,0,0,4166051,6418867200,7768025600,45815586816,11551300,1991863808,0,0,NaN,2.56296,2.57492,2.63721
Somalia,22,2.56464,0.658468,0,17840278,153024,142438256,195536464,341966080,274158112,883124224,0,0,0,NaN,2.57116,1.99532,1.63067
Chad,23,2.5363,0.929844,0,0,0,18643212,228263712,37929668,49812760,218976960,32469414,4361809,24558844,NaN,2.60227,2.15852,2.71988
Afghanistan,24,2.47833,0.488814,0,0,0,437920416,7652869632,4847488512,16856516608,1613691264,1225130240,0,0,NaN,2.48077,2.28933,2.40009
Pakistan,25,2.4767,0.472633,0,236487552,0,569913344,20919279616,78614020096,63376756736,14911048704,24,4383706112,0,NaN,2.48341,2.39071,2.40156
Finland,26,2.46159,0.759258,0,17274570,95002512,10734357,424448192,150921264,1006207232,187079200,85778368,42491660,0,NaN,2.3276,2.31865,2.50535
Tajikistan,27,2.45443,0.207387,0,0,0,0,181711680,5477458944,7056955904,0,0,0,0,NaN,2.44262,2.48566,2.57581
Kazakhstan,28,2.43454,0.535649,0,134317728,624452672,2060690560,1937104128,12307910656,16246602752,1430824960,328157376,66375008,19041546,NaN,2.48083,2.26585,2.24049
Syria,29,2.3676,0.4951,0,121976480,0,677825088,4493064192,3395466752,8089140224,303100352,683537920,0,0,NaN,2.37789,2.31416,2.30144
Kyrgyzstan,30,2.31983,0.243221,0,0,0,0,1211871488,5823776768,2980843264,0,0,0,0,NaN,2.31391,2.41468,2.37444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cyprus,171,0.149473,0.358359,0,83319576,0,14495559,0,0,0,0,0,0,0,NaN,0.126581,0.258667,0.176139
Jamaica,172,0.015444,0.0537027,0,812865600,0,0,0,0,0,0,0,0,0,NaN,0.0129437,0.0178729,0.017687
Antigua and Barbuda,173,0,0,0,8026709,0,0,0,0,0,0,0,0,0,NaN,0,0,0
Bahrain,173,0,0,0,413053888,0,0,0,0,0,0,0,0,0,NaN,0,0,0
Barbados,173,0,0,0,69750728,0,0,0,0,0,0,0,0,0,NaN,0,0,0
Comoros,173,0,0,0,11226803,0,0,0,0,0,0,0,0,0,NaN,0,0,0
Dominica,173,0,0,0,4829325,0,0,0,0,0,0,0,0,0,NaN,-,0,0
Malta,173,0,0,0,49969988,0,0,0,0,0,0,0,0,0,NaN,0,0,0
Saint Lucia,173,0,0,0,6852419,0,0,0,0,0,0,0,0,0,NaN,0,0,0
Saint Vincent and the Grenadines,173,0,0,0,3591320,0,0,0,0,0,0,0,0,0,NaN,-,0,0
Cape Verde,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Curacao,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Federated States of Micronesia,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Fiji,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Grenada,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Kiribati,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Maldives,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Marshall Islands,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Mauritius,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Nauru,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Palau,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Saint Kitts and Nevis,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Samoa,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Sao Tome and Principe,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Seychelles,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Solomon Islands,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
The Bahamas,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Tonga,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Tuvalu,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
Vanuatu,174,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-

In [17]:
#Shows countries with greatest drought severity
df2["All sectors"]

Name
Western Sahara                       4.42071
Mauritania                           3.79019
Niger                                3.72379
Senegal                              3.64657
Oman                                 3.41492
Peru                                 3.38979
Egypt                                3.35266
Namibia                                3.299
Qatar                                2.94453
Sudan                                2.94119
United Arab Emirates                 2.91875
Mali                                 2.90066
Armenia                              2.82779
Jordan                               2.80048
Libya                                2.76611
Eritrea                              2.72977
Botswana                             2.70227
Ecuador                              2.64303
Turkmenistan                         2.61929
Iran                                 2.57415
Uzbekistan                           2.56691
Somalia                              2.56464
Chad                                  2.5363
Afghanistan                          2.47833
Pakistan                              2.4767
Finland                              2.46159
Tajikistan                           2.45443
Kazakhstan                           2.43454
Syria                                 2.3676
Kyrgyzstan                           2.31983
                                      ...
Cyprus                              0.149473
Jamaica                             0.015444
Antigua and Barbuda                        0
Bahrain                                    0
Barbados                                   0
Comoros                                    0
Dominica                                   0
Malta                                      0
Saint Lucia                                0
Saint Vincent and the Grenadines           0
Cape Verde                                 -
Curacao                                    -
Federated States of Micronesia             -
Fiji                                       -
Grenada                                    -
Kiribati                                   -
Maldives                                   -
Marshall Islands                           -
Mauritius                                  -
Nauru                                      -
Palau                                      -
Saint Kitts and Nevis                      -
Samoa                                      -
Sao Tome and Principe                      -
Seychelles                                 -
Solomon Islands                            -
The Bahamas                                -
Tonga                                      -
Tuvalu                                     -
Vanuatu                                    -
Name: All sectors, Length: 200, dtype: object

In [8]:
df2["All sectors"].describe()

count     200
unique    174
top         -
freq       20
Name: All sectors, dtype: object

3.) <strong>Wellhead Natural Gas Prices<strong>

In [18]:
#Natural Gas Prices
xls = pd.ExcelFile("C:/Users/Michael/Dropbox/PhD/CU/0 - Courses/1- Fall 2018/Group Project - Solar Desal/Datasets/3 - Natural Gas Prices/Nat Gas by Decade - Dollars per thousand cubic feet.xls")
df3 = pd.read_excel(xls, 'Data 1')

In [19]:
df3

,Date,U.S. Natural Gas Wellhead Price (Dollars per Thousand Cubic Feet),Inflation Multiple,Inflation Adjusted Natural Gas Price,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,2017-06-30,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN
1,2016-06-30,NaN,1.021299,0.000000,NaN,NaN,NaN,NaN,NaN
2,2015-06-30,NaN,1.034187,0.000000,NaN,NaN,NaN,NaN,NaN
3,2014-06-30,NaN,1.035415,0.000000,NaN,NaN,NaN,NaN,NaN
4,2013-06-30,NaN,1.052211,0.000000,NaN,NaN,NaN,NaN,NaN
5,2012-06-30,2.66,1.067624,2.839879,NaN,NaN,NaN,NaN,NaN
6,2011-06-30,3.95,1.089718,4.304385,NaN,NaN,NaN,NaN,NaN
7,2010-06-30,4.48,1.124115,5.036035,NaN,NaN,NaN,NaN,NaN
8,2009-06-30,3.67,1.142553,4.193171,NaN,NaN,NaN,Back to Contents,Data 1: U.S. Natural Gas Wellhead Price (Dolla...
9,2008-06-30,7.97,1.138489,9.073754,NaN,NaN,NaN,Sourcekey,N9190US3
10,2007-06-30,6.25,1.182201,7.388759,NaN,NaN,NaN,NaN,NaN
11,2006-06-30,6.39,1.215873,7.769429,NaN,NaN,NaN,NaN,NaN
12,2005-06-30,7.33,1.255095,9.199844,NaN,NaN,NaN,NaN,NaN
13,2004-06-30,5.46,1.297618,7.084993,NaN,NaN,NaN,NaN,NaN
14,2003-06-30,4.88,1.332464,6.502422,NaN,NaN,NaN,NaN,NaN
15,2002-06-30,2.95,1.362686,4.019924,NaN,NaN,NaN,NaN,NaN
16,2001-06-30,4.00,1.384077,5.536307,NaN,NaN,NaN,NaN,NaN
17,2000-06-30,3.68,1.423461,5.238337,NaN,NaN,NaN,NaN,NaN
18,1999-06-30,2.19,1.471309,3.222166,NaN,NaN,NaN,NaN,NaN
19,1998-06-30,1.96,1.503804,2.947455,NaN,NaN,NaN,NaN,NaN
20,1997-06-30,2.32,1.527227,3.543168,NaN,NaN,NaN,NaN,NaN
21,1996-06-30,2.17,1.562269,3.390124,NaN,NaN,NaN,NaN,NaN
22,1995-06-30,1.55,1.608399,2.493018,NaN,NaN,NaN,NaN,NaN
23,1994-06-30,1.85,1.653981,3.059865,NaN,NaN,NaN,NaN,NaN
24,1993-06-30,2.04,1.696332,3.460518,NaN,NaN,NaN,NaN,NaN
25,1992-06-30,1.74,1.747113,3.039977,NaN,NaN,NaN,NaN,NaN
26,1991-06-30,1.64,1.799706,2.951518,NaN,NaN,NaN,NaN,NaN
27,1990-06-30,1.71,1.875440,3.207002,NaN,NaN,NaN,NaN,NaN
28,1989-06-30,1.69,1.976774,3.340748,NaN,NaN,NaN,NaN,NaN
29,1988-06-30,1.69,2.072020,3.501714,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
75,1942-06-30,0.05,15.038037,0.751902,NaN,NaN,NaN,NaN,NaN
76,1941-06-30,0.05,16.674830,0.833741,NaN,NaN,NaN,NaN,NaN
77,1940-06-30,0.05,17.508571,0.875429,NaN,NaN,NaN,NaN,NaN
78,1939-06-30,0.05,17.634532,0.881727,NaN,NaN,NaN,NaN,NaN
79,1938-06-30,0.05,17.384397,0.869220,NaN,NaN,NaN,NaN,NaN
80,1937-06-30,0.05,17.022222,0.851111,NaN,NaN,NaN,NaN,NaN
81,1936-06-30,0.06,17.634532,1.058072,NaN,NaN,NaN,NaN,NaN
82,1935-06-30,0.06,17.891971,1.073518,NaN,NaN,NaN,NaN,NaN
83,1934-06-30,0.06,18.292537,1.097552,NaN,NaN,NaN,NaN,NaN
84,1933-06-30,0.06,18.855385,1.131323,NaN,NaN,NaN,NaN,NaN
85,1932-06-30,0.06,17.891971,1.073518,NaN,NaN,NaN,NaN,NaN
86,1931-06-30,0.07,16.126316,1.128842,NaN,NaN,NaN,NaN,NaN
87,1930-06-30,0.08,14.677844,1.174228,NaN,NaN,NaN,NaN,NaN
88,1929-06-30,0.08,14.334503,1.146760,NaN,NaN,NaN,NaN,NaN
89,1928-06-30,0.09,14.334503,1.290105,NaN,NaN,NaN,NaN,NaN
90,1927-06-30,0.09,14.087356,1.267862,NaN,NaN,NaN,NaN,NaN
91,1926-06-30,0.10,13.848588,1.384859,NaN,NaN,NaN,NaN,NaN
92,1925-06-30,0.09,14.006857,1.260617,NaN,NaN,NaN,NaN,NaN
93,1924-06-30,0.09,14.334503,1.290105,NaN,NaN,NaN,NaN,NaN
94,1923-06-30,0.10,14.334503,1.433450,NaN,NaN,NaN,NaN,NaN
95,1922-06-30,0.11,14.590476,1.604952,NaN,NaN,NaN,NaN,NaN
96,NaT,NaN,13.693855,0.000000,NaN,NaN,NaN,NaN,NaN
97,NaT,NaN,12.256000,0.000000,NaN,NaN,NaN,NaN,NaN
98,NaT,NaN,14.168786,0.000000,NaN,NaN,NaN,NaN,NaN
99,NaT,NaN,16.233113,0.000000,NaN,NaN,NaN,NaN,NaN
100,NaT,NaN,19.150000,0.000000,NaN,NaN,NaN,NaN,NaN
101,NaT,NaN,22.488073,0.000000,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,24.269307,0.000000,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,24.512000,0.000000,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,24.759596,0.000000,NaN,NaN,NaN,NaN,NaN

In [20]:
df3.set_index("Date",inplace=True)
df3["Inflation Adjusted Natural Gas Price"]
#Issue: EIA missing 2013 to 2017 wellhead price

Date
2017-06-30    0.000000
2016-06-30    0.000000
2015-06-30    0.000000
2014-06-30    0.000000
2013-06-30    0.000000
2012-06-30    2.839879
2011-06-30    4.304385
2010-06-30    5.036035
2009-06-30    4.193171
2008-06-30    9.073754
2007-06-30    7.388759
2006-06-30    7.769429
2005-06-30    9.199844
2004-06-30    7.084993
2003-06-30    6.502422
2002-06-30    4.019924
2001-06-30    5.536307
2000-06-30    5.238337
1999-06-30    3.222166
1998-06-30    2.947455
1997-06-30    3.543168
1996-06-30    3.390124
1995-06-30    2.493018
1994-06-30    3.059865
1993-06-30    3.460518
1992-06-30    3.039977
1991-06-30    2.951518
1990-06-30    3.207002
1989-06-30    3.340748
1988-06-30    3.501714
                ...
1942-06-30    0.751902
1941-06-30    0.833741
1940-06-30    0.875429
1939-06-30    0.881727
1938-06-30    0.869220
1937-06-30    0.851111
1936-06-30    1.058072
1935-06-30    1.073518
1934-06-30    1.097552
1933-06-30    1.131323
1932-06-30    1.073518
1931-06-30    1.128842
1930-06-30    1.174228
1929-06-30    1.146760
1928-06-30    1.290105
1927-06-30    1.267862
1926-06-30    1.384859
1925-06-30    1.260617
1924-06-30    1.290105
1923-06-30    1.433450
1922-06-30    1.604952
NaT           0.000000
NaT           0.000000
NaT           0.000000
NaT           0.000000
NaT           0.000000
NaT           0.000000
NaT           0.000000
NaT           0.000000
NaT           0.000000
Name: Inflation Adjusted Natural Gas Price, Length: 105, dtype: float64

4.) <strong>Population<strong> = from 1960 to 2017. Source = World Bank

In [21]:
xls = pd.ExcelFile('C:/Users/Michael/Dropbox/PhD/CU/0 - Courses/1- Fall 2018/Group Project - Solar Desal/Datasets/POPULATION/API_SP.POP.TOTL_DS2_EN_excel_v2.xls')
df4 = pd.read_excel(xls, 'Sheet1')

In [22]:
df4

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,"Population, total",SP.POP.TOTL,5.421100e+04,5.543800e+04,5.622500e+04,5.669500e+04,5.703200e+04,5.736000e+04,...,1.013530e+05,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,1.052640e+05
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8.996351e+06,9.166764e+06,9.345868e+06,9.533954e+06,9.731361e+06,9.938414e+06,...,2.729403e+07,2.800433e+07,2.880317e+07,2.970860e+07,3.069696e+07,3.173169e+07,3.275802e+07,3.373649e+07,3.465603e+07,3.553008e+07
2,Angola,AGO,"Population, total",SP.POP.TOTL,5.643182e+06,5.753024e+06,5.866061e+06,5.980417e+06,6.093321e+06,6.203299e+06,...,2.175942e+07,2.254955e+07,2.336913e+07,2.421856e+07,2.509615e+07,2.599834e+07,2.692047e+07,2.785930e+07,2.881346e+07,2.978419e+07
3,Albania,ALB,"Population, total",SP.POP.TOTL,1.608800e+06,1.659800e+06,1.711319e+06,1.762621e+06,1.814135e+06,1.864791e+06,...,2.947314e+06,2.927519e+06,2.913021e+06,2.905195e+06,2.900401e+06,2.895092e+06,2.889104e+06,2.880703e+06,2.876101e+06,2.873457e+06
4,Andorra,AND,"Population, total",SP.POP.TOTL,1.341100e+04,1.437500e+04,1.537000e+04,1.641200e+04,1.746900e+04,1.854900e+04,...,8.386100e+04,8.446200e+04,8.444900e+04,8.375100e+04,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,7.696500e+04
5,Arab World,ARB,"Population, total",SP.POP.TOTL,9.249093e+07,9.504450e+07,9.768229e+07,1.004111e+08,1.032399e+08,1.061750e+08,...,3.398255e+08,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08
6,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,9.263400e+04,1.010780e+05,1.124720e+05,1.255660e+05,1.385290e+05,1.503620e+05,...,6.894278e+06,7.666393e+06,8.270684e+06,8.672475e+06,8.900453e+06,9.006263e+06,9.070867e+06,9.154302e+06,9.269612e+06,9.400145e+06
7,Argentina,ARG,"Population, total",SP.POP.TOTL,2.061908e+07,2.095308e+07,2.128768e+07,2.162184e+07,2.195393e+07,2.228339e+07,...,4.038239e+07,4.079941e+07,4.122389e+07,4.165688e+07,4.209674e+07,4.253992e+07,4.298152e+07,4.341776e+07,4.384743e+07,4.427104e+07
8,Armenia,ARM,"Population, total",SP.POP.TOTL,1.874120e+06,1.941491e+06,2.009526e+06,2.077575e+06,2.144998e+06,2.211316e+06,...,2.908220e+06,2.888584e+06,2.877311e+06,2.875581e+06,2.881922e+06,2.893509e+06,2.906220e+06,2.916950e+06,2.924816e+06,2.930450e+06
9,American Samoa,ASM,"Population, total",SP.POP.TOTL,2.001300e+04,2.048600e+04,2.111700e+04,2.188200e+04,2.269800e+04,2.352000e+04,...,5.703000e+04,5.622700e+04,5.563700e+04,5.532000e+04,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,5.564100e+04
10,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,5.533900e+04,5.614400e+04,5.714400e+04,5.829400e+04,5.952400e+04,6.078100e+04,...,9.247800e+04,9.358100e+04,9.466100e+04,9.571900e+04,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,1.020120e+05
11,Australia,AUS,"Population, total",SP.POP.TOTL,1.027648e+07,1.048300e+07,1.074200e+07,1.095000e+07,1.116700e+07,1.138800e+07,...,2.124920e+07,2.169170e+07,2.203175e+07,2.234002e+07,2.274248e+07,2.314590e+07,2.350414e+07,2.385078e+07,2.421081e+07,2.459893e+07
12,Austria,AUT,"Population, total",SP.POP.TOTL,7.047539e+06,7.086299e+06,7.129864e+06,7.175811e+06,7.223801e+06,7.270889e+06,...,8.321496e+06,8.343323e+06,8.363404e+06,8.391643e+06,8.429991e+06,8.479823e+06,8.546356e+06,8.642699e+06,8.736668e+06,8.809212e+06
13,Azerbaijan,AZE,"Population, total",SP.POP.TOTL,3.895396e+06,4.030320e+06,4.171425e+06,4.315128e+06,4.456689e+06,4.592610e+06,...,8.763400e+06,8.947243e+06,9.054332e+06,9.173082e+06,9.295784e+06,9.416801e+06,9.535079e+06,9.649341e+06,9.757812e+06,9.862429e+06
14,Burundi,BDI,"Population, total",SP.POP.TOTL,2.786106e+06,2.839666e+06,2.893669e+06,2.949926e+06,3.010859e+06,3.077876e+06,...,8.212264e+06,8.489031e+06,8.766930e+06,9.043508e+06,9.319710e+06,9.600186e+06,9.891790e+06,1.019927e+07,1.052412e+07,1.086424e+07
15,Belgium,BEL,"Population, total",SP.POP.TOTL,9.153489e+06,9.183948e+06,9.220578e+06,9.289770e+06,9.378113e+06,9.463667e+06,...,1.070997e+07,1.079649e+07,1.089559e+07,1.104774e+07,1.112825e+07,1.118282e+07,1.120906e+07,1.127420e+07,1.133142e+07,1.137207e+07
16,Benin,BEN,"Population, total",SP.POP.TOTL,2.431622e+06,2.465867e+06,2.502896e+06,2.542859e+06,2.585965e+06,2.632356e+06,...,8.696916e+06,8.944706e+06,9.199259e+06,9.460802e+06,9.729160e+06,1.000445e+07,1.028671e+07,1.057595e+07,1.087230e+07,1.117569e+07
17,Burkina Faso,BFA,"Population, total",SP.POP.TOTL,4.829288e+06,4.894580e+06,4.960326e+06,5.027821e+06,5.098890e+06,5.174870e+06,...,1.468973e+07,1.514110e+07,1.560522e+07,1.608190e+07,1.657122e+07,1.707272e+07,1.758598e+07,1.811062e+07,1.864643e+07,1.919338e+07
18,Bangladesh,BGD,"Population, total",SP.POP.TOTL,4.819975e+07,4.959280e+07,5.103014e+07,5.253242e+07,5.412910e+07,5.583404e+07,...,1.488058e+08,1.504547e+08,1.521491e+08,1.539119e+08,1.557271e+08,1.575713e+08,1.594053e+08,1.612009e+08,1.629516e+08,1.646698e+08
19,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,8.204168e+06,...,7.492561e+06,7.444443e+06,7.395599e+06,7.348328e+06,7.305888e+06,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,7.075991e+06
20,Bahrain,BHR,"Population, total",SP.POP.TOTL,1.624270e+05,1.678940e+05,1.731440e+05,1.781400e+05,1.828870e+05,1.874310e+05,...,1.114590e+06,1.185029e+06,1.240862e+06,1.278269e+06,1.300217e+06,1.315411e+06,1.336397e+06,1.371855e+06,1.425171e+06,1.492584e+06
21,"Bahamas, The",BHS,"Population, total",SP.POP.TOTL,1.095280e+05,1.151080e+05,1.210830e+05,1.273330e+05,1.336980e+05,1.400540e+05,...,3.486760e+05,3.548560e+05,3.608320e+05,3.665680e+05,3.720390e+05,3.772400e+05,3.821690e+05,3.868380e+05,3.912320e+05,3.953610e+05
22,Bosnia and Herzegovina,BIH,"Population, total",SP.POP.TOTL,3.225668e+06,3.288602e+06,3.353226e+06,3.417574e+06,3.478995e+06,3.535640e+06,...,3.763599e+06,3.746561e+06,3.722084e+06,3.688865e+06,3.648200e+06,3.604999e+06,3.566002e+06,3.535961e+06,3.516816e+06,3.507017e+06
23,Belarus,BLR,"Population, total",SP.POP.TOTL,8.198000e+06,8.271216e+06,8.351928e+06,8.437232e+06,8.524224e+06,8.610000e+06,...,9.527985e+06,9.506765e+06,9.490583e+06,9.473172e+06,9.464495e+06,9.465997e+06,9.474511e+06,9.489616e+06,9.501534e+06,9.507875e+06
24,Belize,BLZ,"Population, total",SP.POP.TOTL,9.206400e+04,9.470300e+04,9.738400e+04,1.001640e+05,1.030690e+05,1.061190e+05,...,3.061650e+05,3.139290e+05,3.216080e+05,3.291920e+05,3.367010e+05,3.441810e+05,3.516940e+05,3.592880e+05,3.669540e+05,3.746810e+05
25,Bermuda,BMU,"Population, total",SP.POP.TOTL,4.440000e+04,4.550000e+04,4.660000e+04,4.770000e+04,4.890000e+04,5.010000e+04,...,6.527300e+04,6.563600e+04,6.512400e+04,6.456400e+04,6.479800e+04,6.500100e+04,6.513900e+04,6.523900e+04,6.534100e+04,6.544100e+04
26,Bolivia,BOL,"Population, total",SP.POP.TOTL,3.693449e+06,3.764813e+06,3.838097e+06,3.913395e+06,3.990857e+06,4.070590e+06,...,9.599855e+06,9.758748e+06,9.918242e+06,1.007834e+07,1.023900e+07,1.040026e+07,1.056216e+07,1.072470e+07,1.088788e+07,1.105160e+07
27,Brazil,BRA,"Population, total",SP.POP.TOTL,7.220755e+07,7.435176e+07,7.657325e+07,7.885402e+07,8.116865e+07,8.349802e+07,...,1.929790e+08,1.948960e+08,1.967963e+08,1.986867e+08,2.005610e+08,2.024086e+08,2.042131e+08,2.059621e+08,2.076529e+08,2.092883e+08
28,Barbados,BRB,"Population, total",SP.POP.TOTL,2.309390e+05,2.316780e+05,2.325860e+05,2.335870e+05,2.345470e+05,2.353740e+05,...,2.773190e+05,2.784700e+05,2.795690e+05,2.806010e+05,2.815850e+05,2.825090e+05,2.833850e+05,2.842170e+05,2.849960e+05,2.857190e+05
29,Brunei Darussalam,BRN,"Population, total",SP.POP.TOTL,8.174500e+04,8.559600e+04,8.951600e+04,9.357600e+04,9.784800e+04,1.024250e+05,...,3.792520e+05,3.837720e+05,3.886620e+05,3.940130e+05,3.997480e+05,4.057160e+05,4.117040e+05,4.175420e+05,4.231960e+05,4.286970e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Population, total",SP.POP.TOTL,2.103576e+08,2.162859e+08,2.223965e+08,2.286630e+08,2.350485e+08,2.415251e+08,...,5.659562e+08,5.731253e+08,5.802468e+08,5.873151e+08,5.943307e+08,6.012772e+08,6.081360e+08,6.148920e+08,6.215349e+08,6.280598e+08
235,Timor-Leste,TLS,"Population, total",SP.POP.TOTL,4.999500e+05,5.088450e+05,5.181070e+05,5.277490e+05,5.377860e+05,5.482180e+05,...,1.078110e+06,1.092021e+06,1.109591e+06,1.131523e+06,1.156760e+06,1.184366e+06,1.212814e+06,1.240977e+06,1.268671e+06,1.296311e+06
236,Middle East & North Africa (IDA & IBRD countries),TMN,"Population, total",SP.POP.TOTL,9.783777e+07,1.004585e+08,1.031472e+08,1.059144e+08,1.087749e+08,1.117382e+08,...,3.199345e+08,3.257867e+08,3.317705e+08,3.378950e+08,3.441488e+08,3.504715e+08,3.567833e+08,3.630272e+08,3.691675e+08,3.752170e+08
237,Tonga,TON,"Population, total",SP.POP.TOTL,6.160100e+04,6.374500e+04,6.625900e+04,6.900500e+04,7.175700e+04,7.436200e+04,...,1.030050e+05,1.036040e+05,1.041370e+05,1.045770e+05,1.049510e+05,1.053280e+05,1.057820e+05,1.063640e+05,1.071220e+05,1.080200e+05
238,South Asia (IDA & IBRD),TSA,"Population, total",SP.POP.TOTL,5.718357e+08,5.838941e+08,5.964139e+08,6.093918e+08,6.228226e+08,6.367018e+08,...,1.584359e+09,1.607664e+09,1.630807e+09,1.653799e+09,1.676615e+09,1.699310e+09,1.721848e+09,1.744200e+09,1.766394e+09,1.788389e+09
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Population, total",SP.POP.TOTL,2.285860e+08,2.340086e+08,2.396471e+08,2.455033e+08,2.515764e+08,2.578686e+08,...,8.309656e+08,8.539537e+08,8.776284e+08,9.019899e+08,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09
240,Trinidad and Tobago,TTO,"Population, total",SP.POP.TOTL,8.484790e+05,8.653600e+05,8.800230e+05,8.925690e+05,9.032750e+05,9.124170e+05,...,1.315372e+06,1.321618e+06,1.328100e+06,1.334788e+06,1.341588e+06,1.348248e+06,1.354493e+06,1.360092e+06,1.364962e+06,1.369125e+06
241,Tunisia,TUN,"Population, total",SP.POP.TOTL,4.176266e+06,4.235937e+06,4.303131e+06,4.377637e+06,4.458611e+06,4.545339e+06,...,1.040734e+07,1.052183e+07,1.063993e+07,1.076147e+07,1.088667e+07,1.101456e+07,1.114391e+07,1.127366e+07,1.140325e+07,1.153213e+07
242,Turkey,TUR,"Population, total",SP.POP.TOTL,2.747233e+07,2.814689e+07,2.883280e+07,2.953134e+07,3.024423e+07,3.097296e+07,...,7.044003e+07,7.133918e+07,7.232691e+07,7.340946e+07,7.456987e+07,7.578733e+07,7.703063e+07,7.827147e+07,7.951243e+07,8.074502e+07
243,Tuvalu,TUV,"Population, total",SP.POP.TOTL,6.104000e+03,6.246000e+03,6.389000e+03,6.538000e+03,6.684000e+03,6.815000e+03,...,1.034000e+04,1.044100e+04,1.053100e+04,1.062800e+04,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04
244,Tanzania,TZA,"Population, total",SP.POP.TOTL,1.007451e+07,1.037340e+07,1.068391e+07,1.100590e+07,1.133910e+07,1.168353e+07,...,4.327014e+07,4.466423e+07,4.609859e+07,4.757090e+07,4.908300e+07,5.063660e+07,5.223487e+07,5.387996e+07,5.557220e+07,5.731002e+07
245,Uganda,UGA,"Population, total",SP.POP.TOTL,6.788214e+06,7.006633e+06,7.240174e+06,7.487429e+06,7.746198e+06,8.014401e+06,...,3.166390e+07,3.277190e+07,3.391513e+07,3.509365e+07,3.630680e+07,3.755373e+07,3.883334e+07,4.014487e+07,4.148796e+07,4.286296e+07
246,Ukraine,UKR,"Population, total",SP.POP.TOTL,4.266215e+07,4.320364e+07,4.374947e+07,4.428590e+07,4.479433e+07,4.526194e+07,...,4.625820e+07,4.605330e+07,4.587070e+07,4.570610e+07,4.559330e+07,4.548960e+07,4.527195e+07,4.515403e+07,4.500464e+07,4.483116e+07
247,Upper middle income,UMC,"Population, total",SP.POP.TOTL,1.150569e+09,1.154967e+09,1.171821e+09,1.200060e+09,1.227974e+09,1.256856e+09,...,2.404283e+09,2.422394e+09,2.440543e+09,2.459176e+09,2.478492e+09,2.498184e+09,2.517980e+09,2.537437e+09,2.556922e+09,2.576203e+09
248,Uruguay,URY,"Population, total",SP.POP.TOTL,2.538651e+06,2.571690e+06,2.603887e+06,2.635129e+06,2.665390e+06,2.694537e+06,...,3.350824e+06,3.362755e+06,3.374415e+06,3.385624e+06,3.396777e+06,3.408005e+06,3.419546e+06,3.431552e+06,3.444006e+06,3.456750e+06
249,United States,USA,"Population, total",SP.POP.TOTL,1.806710e+08,1.836910e+08,1.865380e+08,1.892420e+08,1.918890e+08,1.943030e+08,...,3.040940e+08,3.067715e+08,3.093384e+08,3.116443e+08,3.139933e+08,3.162345e+08,3.186225e+08,3.210398e+08,3.234059e+08,3.257192e+08
250,Uzbekistan,UZB,"Population, total",SP.POP.TOTL,8.549493e+06,8.837349e+06,9.138097e+06,9.454250e+06,9.788986e+06,1.014374e+07,...,2.730280e+07,2.776740e+07,2.856240e+07,2.933940e+07,2.977450e+07,3.024320e+07,3.075770e+07,3.129890e+07,3.184790e+07,3.238720e+07
251,St. Vincent and the Grenadines,VCT,"Population, total",SP.POP.TOTL,8.094900e+04,8.214200e+04,8.320600e+04,8.416700e+04,8.506900e+04,8.597000e+04,...,1.091650e+05,1.092530e+05,1.093150e+05,1.093410e+05,1.093280e+05,1.093200e+05,1.093570e+05,1.094550e+05,1.096430e+05,1.098970e+05
252,"Venezuela, RB",VEN,"Population, total",SP.POP.TOTL,8.146847e+06,8.461685e+06,8.790589e+06,9.130349e+06,9.476252e+06,9.824692e+06,...,2.814170e+07,2.858732e+07,2.902803e+07,2.946329e+07,2.989308e+07,3.031785e+07,3.073838e+07,3.115513e+07,3.156818e+07,3.197706e+07
253,British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,8.033000e+03,8.155000e+03,8.298000e+03,8.452000e+03,8.627000e+03,8.814000e+03,...,2.560400e+04,2.644700e+04,2.722400e+04,2.790100e+04,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,3.119600e+04
254,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,3.250000e+04,3.430000e+04,3.500000e+04,3.980000e+04,4.080000e+04,4.350000e+04,...,1.083990e+05,1.084050e+05,1.083580e+05,1.082920e+05,1.081910e+05,1.080440e+05,1.078840e+05,1.077100e+05,1.075100e+05,1.072680e+05
255,Vietnam,VNM,"Population, total",SP.POP.TOTL,3.267063e+07,3.366677e+07,3.468416e+07,3.572209e+07,3.678098e+07,3.786001e+07,...,8.670780e+07,8.756541e+07,8.847251e+07,8.943664e+07,9.045188e+07,9.149772e+07,9.254492e+07,9.357157e+07,9.456907e+07,9.554080e+07
256,Vanuatu,VUT,"Population, total",SP.POP.TOTL,6.369900e+04,6.571300e+04,6.780800e+04,6.996400e+04,7.213100e+04,7.428900e+04,...,2.253400e+05,2.307850e+05,2.362950e+05,2.418710e+05,2.474850e+05,2.531420e+05,2.588500e+05,2.646030e+05,2.704020e+05,2.762440e+05
257,World,WLD,"Population, total",SP.POP.TOTL,3.032160e+09,3.073369e+09,3.126510e+09,3.191786e+09,3.257460e+09,3.324545e+09,...,6.766297e+09,6.849569e+09,6.932870e+09,7.014984e+09,7.099558e+09,7.185138e+09,7.271323e+09,7.357559e+09,7.444157e+09,7.530360e+09
258,Samoa,WSM,"Population, total",SP.POP.TOTL,1.086460e+05,1.121190e+05,1.157880e+05,1.195610e+05,1.233540e+05,1.270680e+05,...,1.835260e+05,1.848260e+05,1.862050e+05,1.876650e+05,1.891940e+05,1.907570e+05,1.922900e+05,1.937590e+05,1.951250e+05,1.964400e+05
259,Kosovo,XKX,"Population, total",SP.POP.TOTL,9.470000e+05,9.660000e+05,9.940000e+05,1.022000e+06,1.050000e+06,1.078000e+06,...,1.747383e+06,1.761474e+06,1.775680e+06,1.791000e+06,1.805200e+06,1.824100e+06,1.821800e+06,1.801800e+06,1.816200e+06,1.830700e+06
260,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5.172135e+06,5.260501e+06,5.351799e+06,5.446063e+06,5.543339e+06,5.643643e+06,...,2.235639e+07,2.297493e+07,2.360678e+07,2.425221e+07,2.490997e+07,2.557632e+07,2.624633e+07,2.691621e+07,2.758421e+07,2.825042e+07
261,South Africa,ZAF,"Population, total",SP.POP.TOTL,1.745686e+07,1.792067e+07,1.840161e+07,1.889928e+07,1.941298e+07,1.994230e+07,...,5.041213e+07,5.097082e+07,5.158466e+07,5.226352e+07,5.299821e+07,5.376740e+07,5.453957e+07,5.529122e+07,5.601547e+07,5.671716e+07
262,Zambia,ZMB,"Population, total",SP.POP.TOTL,3.044846e+06,3.140264e+06,3.240587e+06,3.345145e+06,3.452942e+06,3.563407e+06,...,1.308252e+07,1.345642e+07,1.385003e+07,1.426476e+07,1.469994e+07,1.515321e+07,1.562097e+07,1.610059e+07,1.659139e+07,1.709413e+07
263,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.747369e+06,3.870756e+06,3.999419e+06,4.132756e+06,4.269863e+06,4.410212e+06,...,1.355847e+07,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07

In [23]:
df4.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
count,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,2.600000e+02,...,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.620000e+02,2.620000e+02,2.620000e+02,2.620000e+02,2.620000e+02,2.620000e+02
mean,1.178154e+08,1.193987e+08,1.215153e+08,1.241500e+08,1.268056e+08,1.295275e+08,1.323946e+08,1.352566e+08,1.381695e+08,1.412246e+08,...,2.701044e+08,2.736129e+08,2.771430e+08,2.806617e+08,2.853395e+08,2.890142e+08,2.927178e+08,2.964305e+08,3.001647e+08,3.038948e+08
std,3.718574e+08,3.763198e+08,3.828766e+08,3.914229e+08,4.000141e+08,4.088431e+08,4.182402e+08,4.275910e+08,4.371472e+08,4.471854e+08,...,8.590759e+08,8.695747e+08,8.801411e+08,8.907482e+08,9.031121e+08,9.140650e+08,9.250832e+08,9.361120e+08,9.471972e+08,9.582705e+08
min,4.279000e+03,4.453000e+03,4.566000e+03,4.656000e+03,4.748000e+03,4.841000e+03,4.936000e+03,5.033000e+03,5.161000e+03,5.303000e+03,...,9.947000e+03,9.945000e+03,1.002500e+04,1.005700e+04,1.027900e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04
25%,5.184015e+05,5.301480e+05,5.426568e+05,5.559520e+05,5.684168e+05,5.727790e+05,5.786500e+05,5.882328e+05,6.257960e+05,6.567582e+05,...,1.363216e+06,1.425982e+06,1.443678e+06,1.465471e+06,1.415726e+06,1.431560e+06,1.447306e+06,1.471523e+06,1.522803e+06,1.577113e+06
50%,3.669524e+06,3.734206e+06,3.839584e+06,3.955168e+06,4.074411e+06,4.170862e+06,4.235562e+06,4.300502e+06,4.367325e+06,4.449014e+06,...,9.219637e+06,9.298515e+06,9.378126e+06,9.460802e+06,9.624267e+06,9.746730e+06,9.879129e+06,1.002115e+07,1.012427e+07,1.018073e+07
75%,2.532754e+07,2.611541e+07,2.690508e+07,2.770050e+07,2.847884e+07,2.924750e+07,2.999693e+07,3.059503e+07,3.120239e+07,3.179527e+07,...,4.994594e+07,5.038575e+07,5.087028e+07,5.140827e+07,5.249529e+07,5.318760e+07,5.396340e+07,5.493841e+07,5.590466e+07,5.716180e+07
max,3.032160e+09,3.073369e+09,3.126510e+09,3.191786e+09,3.257460e+09,3.324545e+09,3.394784e+09,3.464689e+09,3.535355e+09,3.610179e+09,...,6.766297e+09,6.849569e+09,6.932870e+09,7.014984e+09,7.099558e+09,7.185138e+09,7.271323e+09,7.357559e+09,7.444157e+09,7.530360e+09

5.) <strong> Population from UN (1950 to 2015)

In [39]:
xlsx = pd.ExcelFile('C:/Users/Michael/Dropbox/PhD/CU/0 - Courses/1- Fall 2018/Group Project - Solar Desal/Datasets/POPULATION/WPP2017_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx')
df5 = pd.read_excel(xlsx, 'ESTIMATES')

In [41]:
df5

,,,,,"Total population, both sexes combined, as of 1 July (thousands)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
Index,Variant,Area,Notes,Country code,1950.000,1951.000,1952.000,1953.000,1954.000,1955.000,1956.000,1957.000,1958.000,1959.000,...,2006.000,2007.000,2008.000,2009.000,2010.000,2011.000,2012.000,2013.000,2014.000,2015.000
1,Estimates,WORLD,NaN,900,2536274.721,2583816.786,2630584.384,2677230.358,2724302.468,2772242.535,2821383.444,2871952.278,2924081.243,2977824.686,...,6623847.913,6706418.593,6789771.253,6873741.054,6958169.159,7043008.586,7128176.935,7213426.452,7298453.033,7383008.820
2,Estimates,More developed regions,a,901,814865.069,824212.665,834074.389,844263.515,854631.777,865069.444,875507.091,885913.898,896292.115,906668.496,...,1215324.559,1220392.009,1225552.166,1230533.857,1235142.506,1239297.769,1243054.571,1246519.987,1249863.519,1253206.546
3,Estimates,Less developed regions,b,902,1721409.652,1759604.121,1796509.995,1832966.843,1869670.691,1907173.091,1945876.353,1986038.380,2027789.128,2071156.190,...,5408523.354,5486026.584,5564219.087,5643207.197,5723026.653,5803710.817,5885122.364,5966906.465,6048589.514,6129802.274
4,Estimates,Least developed countries,c,941,195259.056,199052.136,202904.860,206885.020,211045.058,215421.063,220033.004,224884.923,229967.077,235259.472,...,772488.966,790978.141,809730.997,828953.320,848791.962,869298.106,890423.474,912093.996,934192.321,956631.108
5,Estimates,"Less developed regions, excluding least developed countries",d,934,1526150.596,1560551.985,1593605.135,1626081.823,1658625.633,1691752.028,1725843.349,1761153.457,1797822.051,1835896.718,...,4636034.388,4695048.443,4754488.090,4814253.877,4874234.691,4934412.711,4994698.890,5054812.469,5114397.193,5173171.166
6,Estimates,"Less developed regions, excluding China",NaN,948,1157196.536,1179836.180,1203955.385,1229495.321,1256404.335,1284636.948,1314154.920,1344926.320,1376925.489,1410131.190,...,4049235.086,4118990.845,4189420.663,4260613.466,4332606.955,4405430.289,4478990.918,4553048.983,4627282.130,4701441.323
7,Estimates,High-income countries,e,1503,672895.958,680630.360,688858.965,697440.327,706262.038,715241.145,724324.981,733489.975,742737.736,752087.820,...,1114996.070,1123635.564,1132346.742,1140755.107,1148592.393,1155747.285,1162295.164,1168383.994,1174248.893,1180060.957
8,Estimates,Middle-income countries,e,1517,1734480.842,1772394.343,1808889.488,1844730.274,1880558.365,1916892.378,1954124.307,1992523.405,2032248.837,2073370.392,...,5004220.786,5064199.911,5124552.316,5185424.323,5246881.509,5308974.416,5371564.898,5434287.584,5496648.665,5558263.979
9,Estimates,Upper-middle-income countries,e,1502,956203.656,980195.343,1001876.475,1022053.675,1041402.171,1060465.450,1079650.980,1099234.604,1119374.513,1140134.427,...,2415538.091,2433501.344,2451690.235,2470293.547,2489411.123,2509105.054,2529239.069,2549461.847,2569293.476,2588362.980
10,Estimates,Lower-middle-income countries,e,1501,778277.186,792199.000,807013.013,822676.599,839156.194,856426.928,874473.327,893288.801,912874.324,933235.965,...,2588682.695,2630698.567,2672862.081,2715130.776,2757470.386,2799869.362,2842325.829,2884825.737,2927355.189,2969900.999
11,Estimates,Low-income countries,e,1500,128096.648,129969.107,131991.799,134194.006,136593.546,139196.080,141995.133,144972.227,148099.273,151341.932,...,502059.411,515977.457,530237.548,544900.284,560007.444,575572.515,591576.162,607987.351,624759.914,641858.608
12,Estimates,Sub-Saharan Africa,f,947,179621.076,183039.180,186625.519,190377.650,194295.351,198379.925,202635.053,207066.077,211680.109,216485.360,...,757212.872,778189.569,799848.676,822170.425,845136.154,868747.940,893001.485,917862.127,943284.908,969234.251
13,Estimates,AFRICA,NaN,903,228670.019,233277.049,238113.121,243177.791,248471.497,253995.025,259750.195,265739.281,271965.261,278431.545,...,948156.166,972265.961,997144.670,1022858.654,1049446.344,1076933.813,1105285.268,1134398.192,1164129.789,1194369.908
14,Estimates,Eastern Africa,NaN,910,66758.254,68208.356,69711.520,71272.418,72895.738,74585.806,76346.981,78183.385,80098.967,82097.498,...,309313.054,318329.032,327631.032,337191.043,346987.498,357015.563,367279.164,377775.443,388502.716,399458.026
15,Estimates,Burundi,NaN,108,2308.920,2359.123,2403.511,2445.420,2487.390,2531.184,2577.735,2627.233,2679.141,2732.438,...,7675.338,7939.573,8212.264,8489.031,8766.930,9043.508,9319.710,9600.186,9891.790,10199.270
16,Estimates,Comoros,NaN,174,159.459,163.139,166.541,169.752,172.853,175.903,178.946,181.992,185.043,188.097,...,626.425,641.620,657.229,673.252,689.692,706.569,723.868,741.500,759.385,777.424
17,Estimates,Djibouti,NaN,262,62.001,63.306,64.750,66.269,67.872,69.589,71.497,73.702,76.353,79.612,...,796.208,809.402,822.934,836.840,851.146,865.937,881.185,896.688,912.164,927.414
18,Estimates,Eritrea,NaN,232,1142.148,1159.798,1179.537,1201.124,1224.384,1249.193,1275.534,1303.420,1332.953,1364.276,...,4066.648,4153.332,4232.636,4310.334,4390.840,4474.690,4560.977,4650.998,4746.045,4846.976
19,Estimates,Ethiopia,NaN,231,18128.034,18466.968,18819.700,19184.292,19560.016,19947.292,20347.813,20764.450,21201.034,21661.996,...,78850.689,81000.409,83184.892,85416.253,87702.670,90046.756,92444.183,94887.724,97366.774,99873.033
20,Estimates,Kenya,NaN,404,6076.758,6240.163,6412.363,6593.109,6782.287,6979.931,7186.211,7401.421,7625.995,7860.475,...,37052.050,38085.909,39148.416,40237.204,41350.152,42486.839,43646.629,44826.849,46024.250,47236.259
21,Estimates,Madagascar,NaN,450,4083.554,4168.386,4256.770,4348.720,4444.288,4543.542,4646.576,4753.523,4864.524,4979.753,...,18880.268,19433.523,19996.469,20569.121,21151.640,21743.949,22346.573,22961.146,23589.801,24234.088
22,Estimates,Malawi,NaN,454,2953.871,3008.067,3065.034,3124.734,3187.173,3252.332,3320.220,3390.797,3464.047,3539.970,...,13429.262,13840.969,14271.234,14714.602,15167.095,15627.618,16097.305,16577.147,17068.838,17573.607
23,Estimates,Mauritius,1,480,493.255,506.433,521.188,537.047,553.626,570.648,587.952,605.487,623.276,641.428,...,1228.098,1233.911,1239.293,1244.024,1247.955,1251.023,1253.371,1255.290,1257.219,1259.456
24,Estimates,Mayotte,NaN,175,15.141,15.728,16.443,17.249,18.094,18.985,19.901,20.840,21.832,22.882,...,184.031,190.098,196.279,202.503,208.718,214.923,221.122,227.351,233.638,240.020
25,Estimates,Mozambique,NaN,508,6152.237,6248.717,6352.584,6463.088,6579.634,6701.749,6829.092,6961.486,7098.859,7241.232,...,21547.463,22188.387,22846.758,23524.063,24221.405,24939.005,25676.606,26434.372,27212.382,28010.691
26,Estimates,Réunion,NaN,638,248.110,259.295,268.486,276.526,284.080,291.658,299.571,307.979,316.879,326.167,...,800.543,808.735,816.335,823.537,830.519,837.304,843.907,850.400,856.867,863.363
27,Estimates,Rwanda,NaN,646,2186.185,2250.677,2313.311,2378.445,2448.825,2525.527,2607.950,2693.821,2779.550,2860.691,...,9206.580,9447.402,9708.169,9977.446,10246.842,10516.071,10788.853,11065.151,11345.357,11629.553
28,Estimates,Seychelles,NaN,690,36.325,36.881,37.437,37.964,38.455,38.909,39.334,39.769,40.254,40.826,...,89.659,90.281,90.686,91.034,91.405,91.834,92.285,92.765,93.254,93.742
29,Estimates,Somalia,NaN,706,2264.082,2307.673,2351.929,2397.159,2443.625,2491.520,2540.989,2592.133,2644.994,2699.595,...,10718.317,11038.596,11369.276,11707.990,12053.223,12404.725,12763.776,13132.349,13513.125,13908.129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,Estimates,Saint Pierre and Miquelon,NaN,666,4.571,4.603,4.633,4.660,4.691,4.723,4.766,4.800,4.841,4.882,...,6.260,6.261,6.269,6.277,6.274,6.274,6.276,6.273,6.277,6.290
245,Estimates,United States of America,NaN,840,158804.395,160905.035,163324.851,165988.190,168827.613,171783.842,174805.941,177851.156,180884.458,183877.873,...,297827.356,300595.175,303374.067,306076.362,308641.391,311051.373,313335.423,315536.676,317718.779,319929.162
246,Estimates,OCEANIA,NaN,909,12647.776,12971.297,13275.573,13572.461,13870.902,14176.713,14492.818,14819.081,15152.850,15489.650,...,34138.499,34747.498,35379.766,36014.268,36635.566,37237.877,37824.446,38399.398,38970.389,39542.980
247,Estimates,Australia/New Zealand,NaN,927,10085.342,10360.535,10613.768,10857.134,11099.673,11347.299,11602.730,11865.654,12133.082,12400.154,...,24759.523,25179.815,25620.818,26062.522,26490.126,26898.164,27289.592,27668.256,28041.368,28414.088
248,Estimates,Australia,24,36,8177.342,8412.604,8620.970,8816.902,9011.190,9210.908,9419.268,9635.828,9856.949,10076.741,...,20573.606,20946.664,21342.493,21739.040,22120.064,22479.799,22821.849,23150.729,23474.668,23799.556
249,Estimates,New Zealand,NaN,554,1908.000,1947.931,1992.798,2040.232,2088.483,2136.391,2183.462,2229.826,2276.133,2323.413,...,4185.917,4233.151,4278.325,4323.482,4370.062,4418.365,4467.743,4517.527,4566.700,4614.532
250,Estimates,Melanesia,NaN,928,2165.340,2203.567,2244.826,2288.858,2335.445,2384.384,2435.627,2489.137,2544.919,2603.082,...,8230.174,8415.756,8604.130,8793.691,8983.311,9172.576,9361.723,9551.124,9741.442,9933.150
251,Estimates,Fiji,NaN,242,288.988,296.209,304.814,314.351,324.482,334.976,345.744,356.820,368.319,380.451,...,827.411,834.812,843.340,851.967,859.950,867.086,873.596,879.715,885.806,892.149
252,Estimates,New Caledonia,NaN,540,64.825,64.256,64.408,65.126,66.278,67.748,69.468,71.376,73.449,75.678,...,236.435,240.129,243.786,247.413,251.037,254.657,258.275,261.889,265.497,269.091
253,Estimates,Papua New Guinea,NaN,598,1674.036,1702.370,1731.230,1761.050,1792.140,1824.712,1858.885,1894.678,1931.986,1970.694,...,6470.272,6627.922,6787.187,6947.447,7108.239,7269.348,7430.836,7592.865,7755.785,7919.825
254,Estimates,Solomon Islands,NaN,90,89.794,91.809,94.077,96.560,99.215,102.024,104.965,108.018,111.182,114.465,...,481.422,492.940,504.477,516.079,527.790,539.614,551.531,563.513,575.504,587.482
255,Estimates,Vanuatu,NaN,548,47.697,48.923,50.297,51.771,53.330,54.924,56.565,58.245,59.983,61.794,...,214.634,219.953,225.340,230.785,236.295,241.871,247.485,253.142,258.850,264.603
256,Estimates,Micronesia,NaN,954,155.095,158.150,161.223,164.332,167.560,170.908,174.486,178.265,182.318,186.655,...,502.441,502.012,501.777,502.040,503.056,504.937,507.706,511.151,514.970,518.995
257,Estimates,Guam,NaN,316,59.651,60.262,60.877,61.471,62.053,62.641,63.258,63.926,64.697,65.619,...,158.648,158.855,159.035,159.231,159.444,159.678,159.973,160.375,160.967,161.797
258,Estimates,Kiribati,NaN,296,33.048,33.623,34.286,35.007,35.777,36.596,37.455,38.346,39.268,40.240,...,94.260,96.311,98.440,100.568,102.652,104.656,106.613,108.535,110.458,112.407
259,Estimates,Marshall Islands,NaN,584,13.001,13.222,13.438,13.624,13.784,13.894,13.993,14.083,14.208,14.390,...,52.078,52.137,52.218,52.320,52.425,52.542,52.663,52.793,52.898,52.994
260,Estimates,Micronesia (Fed. States of),NaN,583,32.001,33.408,34.600,35.693,36.777,37.893,39.093,40.373,41.727,43.126,...,105.684,105.078,104.478,103.960,103.616,103.468,103.503,103.702,104.015,104.433
261,Estimates,Nauru,NaN,520,2.954,3.057,3.194,3.337,3.481,3.619,3.756,3.900,4.051,4.232,...,10.071,10.002,9.947,9.945,10.025,10.208,10.478,10.790,11.070,11.260
262,Estimates,Northern Mariana Islands,NaN,580,6.999,7.081,7.215,7.409,7.674,8.010,8.407,8.835,9.280,9.689,...,61.688,59.513,57.431,55.674,54.424,53.786,53.718,54.036,54.468,54.816
263,Estimates,Palau,NaN,585,7.441,7.497,7.613,7.791,8.014,8.255,8.524,8.802,9.087,9.359,...,20.012,20.116,20.228,20.342,20.470,20.599,20.758,20.920,21.094,21.288
264,Estimates,Polynesia,25,957,241.999,249.045,255.756,262.137,268.224,274.122,279.975,286.025,292.531,299.759,...,646.361,649.915,653.041,656.015,659.073,662.200,665.425,668.867,672.609,676.747
265,Estimates,American Samoa,NaN,16,18.940,19.296,19.540,19.677,19.729,19.702,19.652,19.598,19.602,19.734,...,58.650,57.903,57.030,56.227,55.637,55.320,55.230,55.307,55.437,55.537
266,Estimates,Cook Islands,NaN,184,15.077,15.410,15.643,15.844,16.071,16.372,16.738,17.155,17.581,17.967,...,19.696,19.511,19.212,18.868,18.545,18.257,17.996,17.767,17.588,17.449
267,Estimates,French Polynesia,NaN,258,60.266,62.085,63.870,65.593,67.252,68.854,70.429,72.060,73.827,75.806,...,257.832,260.594,263.179,265.581,267.820,269.843,271.703,273.528,275.484,277.690
268,Estimates,Niue,NaN,570,4.667,4.678,4.684,4.686,4.685,4.694,4.700,4.719,4.750,4.788,...,1.662,1.651,1.639,1.636,1.630,1.630,1.623,1.623,1.616,1.629
269,Estimates,Samoa,NaN,882,82.097,84.437,86.819,89.238,91.696,94.208,96.799,99.500,102.353,105.380,...,181.094,182.286,183.526,184.826,186.205,187.665,189.194,190.757,192.290,193.759
270,Estimates,Tokelau,NaN,772,1.566,1.517,1.504,1.521,1.559,1.607,1.671,1.722,1.782,1.823,...,1.167,1.141,1.126,1.126,1.140,1.151,1.167,1.187,1.219,1.252
271,Estimates,Tonga,NaN,776,47.220,49.315,51.170,52.783,54.150,55.323,56.366,57.387,58.508,59.873,...,101.689,102.357,103.005,103.604,104.137,104.577,104.951,105.328,105.782,106.364
272,Estimates,Tuvalu,NaN,798,5.166,5.220,5.293,5.371,5.473,5.569,5.658,5.760,5.864,5.982,...,10.137,10.243,10.340,10.441,10.531,10.628,10.725,10.819,10.908,11.001
273,Estimates,Wallis and Futuna Islands,NaN,876,7.000,7.087,7.233,7.424,7.609,7.793,7.962,8.124,8.264,8.406,...,14.434,14.229,13.984,13.706,13.428,13.129,12.836,12.551,12.285,12.066